### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by qassisju** [qassisju/MI-449-SS17-741-html-meta-elements-_f2DoK#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://qassisju-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

**Comment by KatieMFritz** [comment]
Hi Justin, Stuart swapped this with me for a JavaScript review. 😁 

Great start! Here are some ways to make it better:

### Valid HTML
You're doing something strange with your `<html>` tags - you've got two of them. 🙃 Combine that into one set and be sure to fix your indentation when you do. You can check your code at the [W3 validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fqassisju-kapv98gmwdanx_f2dok.surge.sh%2F) to make sure everything looks good.

There's also two line breaks near the end of your `index.html` that aren't consistent with the rest of your code.
* * *
### Location
I see `geo.position`, but not ICBM. [From the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-meta-elements/3):
> Even though they'll provide the same information, it's good to include both of these elements, because some services might look for one, but not the other.
* * * 
### Open Graph errors
I see this warning when I check your home page on the [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fqassisju-kapv98gmwdanx_f2dok.surge.sh%2F):

> Object at URL 'https://qassisju-kapv98gmwdanx_f2dok.surge.sh/' of type '' is invalid because the given value 'qassisju-kapv98gmwdanx_f2dok.surge.sh' for property 'og:url' could not be parsed as type 'url'.

See if you can fix that, and any other warnings that come up (it's okay not have a `fb:app_id` specified).

Your about page seems to have completely inaccurate Open Graph info. Please make sure you're using these properties correctly for both pages! 😄 
* * *
### Twitter images missing
Your Twitter cards look nice, but I'm not seeing an image for either of them. 🚫  To get images to show up in meta tags, you have to use absolute links, not relative links (so the root URL for your hosted site, then the image file). 
* * *
### Unique title & description for each page
Lastly, as you're making your other updates to the metadata for your site, be sure to follow these guidelines:

Here are some guidelines for writing titles and descriptions for your pages (including `title` and `meta name="description` elements, Twitter metadata, and Facebook (`og`) metadata:

1. **Each page should have a _unique_ title and description that describes that specific page** for people who have no idea what your site is about (because they will see this info on social media or search results before they ever come to your site). From the lesson: 

    > [It's] common for homepages to describe the entire website. On every other page however, this information should be specific to the current page.

2. **Each page should (usually) have _consistent_ titles and descriptions across platforms,** i.e. the Twitter, Open Graph, and general titles and descriptions should all match each other. This helps users figure out whether they've already visited that page. It also makes life easier for you - you can just copy and paste! Once you get into more advanced site development, you can use the same variables across all three places.

3. **Titles and descriptions should be brief.** Different platforms display different amounts of text, but I usually use [50-70 characters for titles, 100-150 characters for descriptions](http://www.thesempost.com/new-title-description-lengths-for-google-seo/). Anything longer will likely get cut off.
* * *
Let me know if you have any questions! Otherwise, please double check your work at the W3, Facebook, and Twitter validators before resubmitting. See you tomorrow! 🌴 🌞

**Comment by qassisju** [comment]
Hopefully these are fixed!

**Comment by KatieMFritz** [comment]
HTML - 👍 

Geo - now I see only `ICBM`, not `geo.position`. Per the lesson, you need both.

Open Graph - [still getting several errors](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fqassisju-kapv98gmwdanx_f2dok.surge.sh%2F)

Twitter - looking good. 🌟 

Title/description content - read my guidelines again. The title/description pairs should usually match for `title`/`meta name="description"`, `twitter`, and `og` properties for each page, and be unique from page to page.

Let me know when you've made updates, or flag me down if you have questions! ✈️

**Comment by qassisju** [comment]
Okay these should be fixed, besides the weird debugging error. That is still being funky, but it seems to be working just fine

**Comment by KatieMFritz** [comment]
Nice job! 👍 

If you add `og` data to a real site sometime, double check it - I'm 75% sure it's just the debugger being weird, but there might be some issue with the way you've done your `og:description`.

But for now, :shipit:!
